# Generated by Django 3.0.6 on 2020-06-01 08:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("id", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("description", models.TextField(null=True)),
                ("serial_number", models.CharField(max_length=64, null=True)),
                ("manufacturer", models.CharField(max_length=32, null=True)),
                ("metadata", django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                (
                    "state",
                    models.TextField(
                        choices=[("ACTIVE", "ACTIVE"), ("DISPOSED", "DISPOSED")], default="ACTIVE", max_length=16
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ("vat", models.DecimalField(decimal_places=4, max_digits=7, null=True)),
                ("asset_keeper", models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
